services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: e-learning-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: e-learning-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    depends_on:
      - mongo
    container_name: e-learning-app-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/