import Link from "next/link";
import { SidebarLayout } from "./_layouts/SidebarLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <div className="flex flex-row w-screen h-screen">
          <SidebarLayout>
            <>
              <Link href="/admin/kpis">KPIs</Link>
              <Link href="/admin/courses">Courses</Link>
            </>
          </SidebarLayout>
          {children}
        </div>
      </body>
    </html>
  );
}
