import { SidebarLayout } from "./_layouts/SidebarLayout";
import { BodyLayout } from "./_layouts/BodyLayout";
import LinkOption from "@/frontend/ui/LinkOption";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <div className="flex flex-row w-screen h-screen">
          <SidebarLayout>
            <LinkOption
              className="text-lg text-text-grayed"
              highlightedClass="text-text-light"
              href="/admin/courses"
            >
              Courses
            </LinkOption>
          </SidebarLayout>
          <BodyLayout>{children}</BodyLayout>
        </div>
      </body>
    </html>
  );
}
